In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
b = a[a < 0]
b

array([-2, -1, -6, -7])

In [4]:
len(b)

4

In [5]:
len(a[a<0])

4

In [6]:
len(a[a>0])

5

In [7]:
pos = a[a>0]
pos

array([ 4, 10, 12, 23,  3])

In [8]:
pos_even = pos[pos % 2 == 0]
pos_even

array([ 4, 10, 12])

In [9]:
pos_even_count = len(pos_even)
pos_even_count

3

In [10]:
plus_three = a + 3
plus_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [11]:
p_t_pos = plus_three[plus_three > 0]
p_t_pos

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [12]:
p_t_pos_count = len(p_t_pos)
p_t_pos_count

10

In [13]:
squared = a**2
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [14]:
import statistics
import math

In [15]:
sq_avg = statistics.mean(squared)
sq_avg

74

In [16]:
sq_stddev = statistics.stdev(squared)
sq_stddev

150.42606157179014

In [17]:
centered = a - statistics.mean(a)
centered

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [18]:
original_avg = np.mean(a)
original_avg

3.0

In [19]:
original_std = np.std(a)
original_std

8.06225774829855

In [20]:
original_z = (a - original_avg) / original_std
original_z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [21]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
sum_of_a = np.sum(a)
sum_of_a

55

In [23]:
min_of_a = np.min(a)
min_of_a

1

In [24]:
max_of_a = np.max(a)
max_of_a

10

In [25]:
mean_of_a = np.mean(a)
mean_of_a

5.5

In [26]:
product_of_a = np.product(a)
product_of_a

3628800

In [27]:
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [28]:
a = np.array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [29]:
re = a[a % 2 != 0]
re

array([ 1,  9, 25, 49, 81])

In [30]:
odds_in_a = a[a % 2 != 0]
odds_in_a

array([ 1,  9, 25, 49, 81])

In [31]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([  4,  16,  36,  64, 100])

In [32]:
b = np.array([[3,4,5],[6,7,8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [33]:
sum_of_b = sum(b[0])
sum_of_b

12

In [34]:
b[0]

array([3, 4, 5])

In [35]:
min_of_b_zero = min(b[0])
min_of_b_zero

3

In [36]:
min_of_b_one = min(b[1])
min_of_b_one

6

In [37]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [38]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [39]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [40]:
s = sum(b[0]) + sum(b[1])

In [41]:
s

33

In [42]:
ss = np.sum(b)

In [43]:
ss

33

In [44]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [45]:
sum_of_b = np.sum(b)
sum_of_b

33

In [46]:
min_of_b = np.min(b)
min_of_b

3

In [47]:
max_of_b = np.max(b)
max_of_b

8

In [48]:
mean_of_b = np.mean(b)
mean_of_b

5.5

In [49]:
product_of_b = np.product(b)
product_of_b

20160

In [50]:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [51]:
odds_in_b= b[b % 2 != 0]
odds_in_b


array([3, 5, 7])

In [52]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

In [53]:
print(np.shape(b))

(2, 3)


In [54]:
b = b.transpose()
b

array([[3, 6],
       [4, 7],
       [5, 8]])

In [55]:
b = b.reshape(1,6)
b

array([[3, 6, 4, 7, 5, 8]])

In [56]:
b = b.reshape(6,1)
b

array([[3],
       [6],
       [4],
       [7],
       [5],
       [8]])

In [57]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.min(c)

1

In [59]:
np.max(c)

9

In [60]:
np.sum(c)

45

In [61]:
np.product(c)

362880

In [62]:
np.std(c)

2.581988897471611

In [63]:
np.var(c)

6.666666666666667

In [64]:
print(np.shape(c))

(3, 3)


In [65]:
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [66]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [67]:
np.dot?

In [68]:
np.sum(c)

45

In [69]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
c * c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [71]:
sum(c*c)

array([ 66,  93, 126])

In [72]:
np.sum(c * np.transpose(c))

261

In [73]:
np.product(c * np.transpose(c))

131681894400

In [74]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [75]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [76]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [77]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [78]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [79]:
neg_d = d[d < 0]
neg_d

array([-90, -30, -45, -45])

In [80]:
d[d<0]

array([-90, -30, -45, -45])

In [81]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [82]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [83]:
len(np.unique(d))

11

In [84]:
np.shape(d)

(3, 6)

In [85]:
np.shape(np.transpose(d))

(6, 3)

In [86]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [87]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])