In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
b = a[a < 0]
b

array([-2, -1, -6, -7])

In [5]:
len(b)

4

In [6]:
len(a[a<0])

4

In [7]:
len(a[a>0])

5

In [9]:
pos = a[a>0]
pos

array([ 4, 10, 12, 23,  3])

In [10]:
pos_even = pos[pos % 2 == 0]
pos_even

array([ 4, 10, 12])

In [12]:
pos_even_count = len(pos_even)
pos_even_count

3

In [13]:
plus_three = a + 3
plus_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [14]:
p_t_pos = plus_three[plus_three > 0]
p_t_pos

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [15]:
p_t_pos_count = len(p_t_pos)
p_t_pos_count

10

In [16]:
squared = a**2
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [32]:
import statistics
import math

In [33]:
sq_avg = statistics.mean(squared)
sq_avg

74

In [36]:
sq_stddev = statistics.stdev(squared)
sq_stddev

150.42606157179014

In [37]:
centered = a - statistics.mean(a)
centered

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [38]:
original_avg = np.mean(a)
original_avg

3.0

In [39]:
original_std = np.std(a)
original_std

8.06225774829855

In [40]:
original_z = (a - original_avg) / original_std
original_z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [41]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [42]:
sum_of_a = np.sum(a)
sum_of_a

55

In [43]:
min_of_a = np.min(a)
min_of_a

1

In [45]:
max_of_a = np.max(a)
max_of_a

10

In [46]:
mean_of_a = np.mean(a)
mean_of_a

5.5

In [47]:
product_of_a = np.product(a)
product_of_a

3628800

In [52]:
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [74]:
a = np.array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [77]:
re = a[a % 2 != 0]
re

array([ 1,  9, 25, 49, 81])

In [78]:
odds_in_a = a[a % 2 != 0]
odds_in_a

array([ 1,  9, 25, 49, 81])

In [80]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([  4,  16,  36,  64, 100])